version: '3'

services:
  db:
    image: postgres:16.3-alpine
    restart: always
    volumes:
      - NEXTCLOUD_DB_PATH:/var/lib/postgresql/data:z
    env_file:
      - db.env
    logging:
      driver: json-file
      options:
        max-file: '2'
        max-size: 50m

  redis:
    image: redis:alpine
    restart: always
    logging:
      driver: json-file
      options:
        max-file: '2'
        max-size: 50m

  app:
    image: nextcloud:28.0.5-fpm
    restart: always
    volumes:
      - NEXTCLOUD_PATH:/var/www/html:z
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    logging:
      driver: json-file
      options:
        max-file: '2'
        max-size: 50m

  web:
    build: ./web
    restart: always
    ports:
      - 9000:80
    volumes:
      - NEXTCLOUD_PATH:/var/www/html:z,ro
    depends_on:
      - app
    logging:
      driver: json-file
      options:
        max-file: '2'
        max-size: 50m

  cron:
    image: nextcloud:28.0.5-fpm
    restart: always
    volumes:
      - NEXTCLOUD_PATH:/var/www/html:z
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
    logging:
      driver: json-file
      options:
        max-file: '2'
        max-size: 50m