version: '3'

services:
  db:
    image: postgres:16.3-alpine
    restart: always
    volumes:
      - /mnt/nextcloud_db:/var/lib/postgresql/data:z
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:28.0.5-fpm
    restart: always
    volumes:
      - /mnt/nextcloud:/var/www/html:z
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis

  web:
    build: ./web
    restart: always
    ports:
      - 9000:80
    volumes:
      - /mnt/hdd_data/nextcloud:/var/www/html:z,ro
    depends_on:
      - app